baseURL = 'https://jeevanmr.com'
languageCode = 'en-us'
title = "Jeevan M R"

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  github = 'jee1mr'                 # github.com/YOUR_GITHUB_ID
  instagram = 'jeevan.mr_'           # instagram.com/YOUR_INSTAGRAM_ID
  linkedin = 'jee1mr'             # linkedin.com/in/YOUR_LINKEDIN_ID
  rss = true                                # show rss icon

  # home page profile
  avatar = '14.jeevan@gmail.com'                 # gravatar email or image url
  name = 'Jeevan M R'
  bio = 'Refactoring life, one commit at a time.'
  mainSections = ["engineering", "essays"]

  # misc
  disableHLJS = false                        # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  gravatarCdn = ''         # e.g. 'https://cdn.v2ex.com/gravatar/'
  math = true                               # enable KaTeX math typesetting globally
  localKatex = false                        # use local KaTeX js/css instead of CDN
  favicon = "favicon.ico"                   # customize the default favicon
  appleTouchIcon = "apple-touch-icon.png"   # customize the default Apple touch icon

  # giscus
[params.giscus]
  repo = 'jee1mr/jee1mr.github.io'                 # see https://giscus.app for more details
  repoId = 'R_kgDOQJ2P9w'
  category = 'Announcements'
  categoryId = 'DIC_kwDOQJ2P984CzJxH'
  strict = '1'
  mapping = 'pathname'
  theme = 'dark_dimmed'
  lang = 'en'
  loading = 'lazy'


[module]
  [[module.imports]]
    path = "github.com/nanxiaobei/hugo-paper"


[caches]
  [caches.images]
    dir = ':cacheDir/images'

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 20

  [[menu.main]]
    identifier = "quotes"
    name = "Quotes"
    url = "/quotes/"
    weight = 30


