baseURL = 'https://blog.jeevanmr.com'
languageCode = 'en-us'
title = 'Jeevan M R'

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  github = 'jee1mr'                 # github.com/YOUR_GITHUB_ID
  instagram = 'jeevan.mr_'           # instagram.com/YOUR_INSTAGRAM_ID
  linkedin = 'jee1mr'             # linkedin.com/in/YOUR_LINKEDIN_ID
  rss = true                                # show rss icon

  # home page profile
  avatar = 'https://media.licdn.com/dms/image/v2/D5603AQGUgvW9naxVJw/profile-displayphoto-shrink_800_800/B56ZNnLyyLGwAc-/0/1732602966357?e=1766016000&v=beta&t=li_0tDvhNmy1SDJuETRYrmc0Zz-wnujT0lLA9x5fuwM'                 # gravatar email or image url
  name = 'Jeevan M R'
  bio = 'Software Engineer by trade. Builder at heart.'

  # misc
  disableHLJS = false                        # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  gravatarCdn = 'GRAVATAR_CDN_LINK'         # e.g. 'https://cdn.v2ex.com/gravatar/'
  math = true                               # enable KaTeX math typesetting globally
  localKatex = false                        # use local KaTeX js/css instead of CDN
  favicon = "favicon.ico"                   # customize the default favicon
  appleTouchIcon = "apple-touch-icon.png"   # customize the default Apple touch icon

  # giscus
[params.giscus]
  repo = 'jee1mr/jee1mr.github.io'                 # see https://giscus.app for more details
  repoId = 'R_kgDOQJ2P9w'
  category = 'Announcements'
  categoryId = 'DIC_kwDOQJ2P984CzJxH'
  strict = '1'
  mapping = 'pathname'
  theme = 'dark_dimmed'
  lang = 'en'
  loading = 'lazy'


[module]
  [[module.imports]]
    path = "github.com/nanxiaobei/hugo-paper"


[caches]
  [caches.images]
    dir = ':cacheDir/images'